Refactor
Kinvey/html5-sdk pull request #12
Opened 2017-02-08 20:24 UTC by thomasconner

#### Description
Refactor code.

2017-02-08 20:41 UTC, tejasranade requested changes

2017-02-08 20:41 UTC, tejasranade commented on src/middleware/src/storage/src/websql.js
> +      throw new Error('A name is required to use the IndexedDB adapter.', name);
@thomasconner  this should say WebSQL, not IndexedDB.

2017-02-08 20:41 UTC, tejasranade commented on src/middleware/src/http.js
> +  const rOpera = /(opera)(?:.*version)?[ /]([\w.]+)/;
@thomasconner is this deliberate? If so, what prompted it?

2017-02-08 20:41 UTC, tejasranade commented on src/middleware/src/storage/src/websql.js
> +      db = global.openDatabase(this.name, 1, '', size);
@thomasconner  What is the third parameter? Can we provide a meaningful value for it?

2017-02-08 20:52 UTC, thomasconner commented on src/middleware/src/storage/src/websql.js
> +      db = global.openDatabase(this.name, 1, '', size);
Let me see if I can think of something useful

2017-02-08 20:53 UTC, thomasconner commented on src/middleware/src/http.js
> +  const rOpera = /(opera)(?:.*version)?[ /]([\w.]+)/;
Is the opera regex deliberate?

2017-02-09 16:38 UTC, thomasconner commented on src/middleware/src/storage/src/websql.js
> +      throw new Error('A name is required to use the IndexedDB adapter.', name);
Fixed

2017-02-09 16:39 UTC, thomasconner commented on src/middleware/src/http.js
> +  const rOpera = /(opera)(?:.*version)?[ /]([\w.]+)/;
@tejasranade Eslint was throwing an error "unnecessary escape character"

2017-02-09 17:58 UTC, tejasranade approved these changes

2017-02-09 17:59 UTC, merged