MLIBZ-1368 Incompatibility issues with  IE 11
Kinvey/html5-sdk pull request #4
Opened 2016-11-14 14:49 UTC by thediycoder

#### Description
This PR fixes incompatibility issues with using `IndexedDB` with IE 11. It also updates the internal error object to correctly extend the native JavaScript `Error` object.

#### Changes
- Do not handle a `blocked` event with the `IndexedDB` adapter. This event will be handled by a `onversionchange` event handler.
- Extend the native JavaScript `Error` object properly.
- Add an e2e test app to use with [BrowserStack](http://browserstack.com) to test SDK against a suite of browsers.

2016-11-16 15:46 UTC, tejasranade requested changes
@thediycoder this looks fine. I left one comment in the package.json where the dependency needs correction.

2016-11-16 15:46 UTC, tejasranade commented on package.json
> +    "kinvey-node-sdk": "../../Node/SDK",
This seems incorrect. Please check.

2016-11-17 14:58 UTC, thediycoder commented on package.json
> +    "kinvey-node-sdk": "../../Node/SDK",
Fixed

2016-11-17 18:41 UTC, tejasranade approved these changes

2016-11-17 18:53 UTC, merged